### ISSUE TITLE
How does one use this when the route is async?

### ISSUE THREAD

**Issue by Pyrolistical** [lykmapipo/mock-express-response#1]
My express route has a async function which on success or failure will set properties on the response.

Right now there is no way to use this library to mock out the response with async code.

For example:
```
router.get('/', (req, res) => {
  someAsyncFunction((err, result) => {
    if (err) {
      return res.sendStatus(500);
    }
    return res.json(result);
  });
});
```

In the unit test the problem is there is no way to know when `response.end()` was called.  The unit test does not know when the json has been set to the response.

**Comment by lykmapipo** [comment]
Hi @Pyrolistical 

My recommendation is to separate `route definition` and `request handler`. This will let you be able to `unit test handler` as below

- route definition
```js
//require handler here
...
router.get('/', handler.index(request,response))
...
```
- Handler definition
```js
module.exports = {
          index: function(request,   response){
              someAsyncFunction(function (err, result) {
                   if (err) {
                             return res.sendStatus(500);
                   }else{
                     return res.json(result);
                  }
              });
          }
}
```

- Then in your handler spec you codes will look like below
```js
  var handler = //require your handler
   var Request = require('mock-express-request');
   var Response = require('mock-express-response');

    it('should be able to response with 201 `created`', function(done) {

        var request = new Request({
            headers: {
                'Accept': 'application/json'
            }
        });

        var response = new Response({
            request: request,
            finish: function() {

               // your assertions here
                expect(response.statusCode).to.be.equal(200);

                expect(response.get('content-type'))
                    .to.be.equal('application/json; charset=utf-8');
                
                //assertion for your response body
                expect(response._getJSON().name).to.equal(data.name);

                done();
            }
        });

        //invoke your handler
        handler.index(request, response);

    });
```

You may check out [express-respond unit test](https://github.com/lykmapipo/express-respond/tree/master/test/unit) to see it in action.

Hope it helps.

**Comment by Pyrolistical** [comment]
I see, you are extending `mock-res` with additional express methods.  Your readme should not explain usages.  It should just refer to `mock-res`, but just list the additional express methods.
