### ISSUE TITLE
response.locals

### ISSUE THREAD

**Issue by seriousManual** [lykmapipo/mock-express-response#10]
The mock Response currently does not support the `locals` property of the native express object.

Currently it is necessary to do something like this:
````javascript
resMock = new ResMock();
resMock.locals = { foo: 'bar' };
````

It would be much nicer if something like this was possible:
````javascript
resMock = new ResMock({
    locals: { foo: 'bar' }
});
````

**Comment by leviwheatcroft** [comment]
looks like you'd literally just need `this.locals = options.locals || {}` [here](https://github.com/lykmapipo/mock-express-response/blob/master/index.js#L53).

**Comment by skypper** [comment]
I opened a small PR with a fix.
Please review and release a new npm package.

**Comment by skypper** [comment]
Thanks for merging https://github.com/lykmapipo/mock-express-response/pull/11.
Could you please publish a new NPM package, Levi?

Happy Holidays!
